# Diese Datei startet ALLE Services des CO2-Ökosystems
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - co2-network

  wallet-backend:
    container_name: wallet-backend
    build: ../services/wallet/backend
    networks:
      - co2-network
    depends_on:
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallet-backend.rule=PathPrefix(`/api/wallet`)"
      - "traefik.http.services.wallet-backend.loadbalancer.server.port=8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - co2-network

  wallet-ui:
    container_name: wallet-ui
    build: ../services/wallet/frontend
    networks:
      - co2-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallet-ui.rule=PathPrefix(`/wallet`)"
      - "traefik.http.middlewares.wallet-ui-stripprefix.stripprefix.prefixes=/wallet"
      - "traefik.http.routers.wallet-ui.middlewares=wallet-ui-stripprefix"
      - "traefik.http.services.wallet-ui.loadbalancer.server.port=3000"

# Das globale Netzwerk, über das alle Container kommunizieren
networks:
  co2-network:
    driver: bridge